version: "3.8"
services:
  backend:
    build:
      context: ./back
    env_file:
      - ./back/.env
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./front
    env_file:
      - ./front/.env
    ports:
      - "80:80"
