FROM node:18-alpine

# Install OpenSSL with apk (Alpine-specific)
RUN apk add --no-cache openssl

WORKDIR /app


# Copy package files
COPY package*.json ./
RUN npm install

# Copy prisma schema and generate client
COPY prisma ./prisma/
RUN npx prisma generate

# Copy source code
COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]