name: Build & Deploy BACKEND to Scaleway
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker image
        working-directory: back
        run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend-image
      - name: Push the Docker Image
        working-directory: back
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend-image

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy on Scaleway Containers
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
