name: Build & Deploy
on:
  push:
    branches:
      - dev

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker image
        working-directory: back
        run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend-image

      - name: Push the Docker Image
        working-directory: back
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend-image

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    name: Deploy Bacnkend on Scaleway
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use CLI
        uses: scaleway/action-scw@v0
        with:
          save-config: true
          export-config: true
          version: v2.24.0
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}

      - name: Delete container if extists
        run: |
          CONTAINER_ID=$(scw container container list | grep container-backend | awk '{print $1}') || true
          if [ ! -z "$CONTAINER_ID" ]; then
            scw container container delete $CONTAINER_ID
          fi

      - name: Create a container
        id: create-container
        run: |
          scw container container create name=container-backend \
          namespace-id=fff60a01-13f1-4d75-99dd-ba21a100f036 \
          registry-image=${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/backend-image:latest \
          min-scale=0 \
          max-scale=1 \
          memory-limit=128 \
          cpu-limit=100 \
          port=3000 \
          environment-variables.JWT_SECRET=${{ secrets.JWT_SECRET }} \
          environment-variables.DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --wait

          CONTAINER_ID=$(scw container container list | grep container-backend | awk '{print $1}')
          BACKEND_URL=$(scw container container get $CONTAINER_ID -o json | jq -r '.domain_name')

          echo "BACKEND_URL=https://${BACKEND_URL}" >> $GITHUB_OUTPUT

  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        working-directory: front
        env:
          BACKEND_URL: ${{ needs.deploy-backend.outputs.BACKEND_URL }}
        run: |
          echo "VITE_API_URL=${BACKEND_URL}" > .env

      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker image
        working-directory: front
        run: |
          docker build \
          --build-arg VITE_API_URL=${BACKEND_URL} \
          -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend-image .

      - name: Push the Docker Image
        working-directory: front
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/frontend-image
