name: Test Backend

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: cd back
      - run: npm ci
      - run: npm test
