name: Test Backend

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci  # ou npm install, selon ce que tu préfères

      - name: Run Backend Tests
        run: |
          cd backend
          npm test
